services:
  backend:
    build:
      context: . # 1. Set build context to repo root
      dockerfile: backend/Dockerfile
    environment:
      MONGO_URI: mongodb://mongo:27017/realtime-whiteboard
      CHOKIDAR_USEPOLLING: "true"
    container_name: whiteboard-api

    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    volumes:
      - ./backend:/app # Mounts backend code to /app
      - ./common:/common
      - /app/node_modules

    command: npm run start-dev

  mongo:
    image: mongo:8

    restart: unless-stopped

    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
